### ISSUE TITLE
Download ROM String missing

### ISSUE THREAD

**Issue by Jaizu** [AospExtended/platform_packages_apps_AEXOTA#5]
I can't locate the "Download ROM" string in the spanish either in the original strings.xml

![string](https://cloud.githubusercontent.com/assets/18596778/23948202/3e5b0f42-0982-11e7-903b-d879dfd87cc2.jpg)

**Comment by ishubhamsingh** [comment]
Because it has been defined in OTA's xml..which is hosted on our servers.ex: http://downloads.aospextended.com/ota/oneplus3
